### ISSUE TITLE
Shazamio stops working

### ISSUE THREAD

**Issue by YashMakan** [dotX12/ShazamIO#10]
It was working perfectly fine but now if I used the example used in pypi i.e,
```
import asyncio
from shazamio import Shazam


async def main():
  shazam = Shazam()
  tracks = await shazam.search_track(query='Lil', limit=5)
  print(tracks)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
Then it is returning `{}`. 
What should I do? btw I am using `shazamio==0.0.2` and `python 3.8.2`

**Comment by dotX12** [comment]
I need more information on why this might not work for you.  I run this code on the most recent version and on 0.0.2 - everything works fine!

**Comment by YashMakan** [comment]
I am sorry the last time I ran the same code and was returning `{}` but now everything is working perfectly fine.
