### ISSUE TITLE
How to directly pass the audio as bytes to recognize?

### ISSUE THREAD

**Issue by YashMakan** [dotX12/ShazamIO#13]
Hi, I am getting audio bytes and I want to pass the bytes directly to recognize without creating a file from the bytes. 
```
result = await shazam.recognize_song(bytes_of_audio_file)
print(result)
```
is there any way to do this?

**Comment by dotX12** [comment]
@YashMakan, Hello, done in version 0.0.6.
https://github.com/dotX12/ShazamIO/releases/tag/0.0.6
https://pypi.org/project/shazamio/0.0.6/
