### ISSUE TITLE
ShazamIO can't recognise some tracks, but Shazam app works well with them

### ISSUE THREAD

**Issue by Vadimkin** [dotX12/ShazamIO#14]
Hello!

Thank you for this very useful package – I use it to recognize streams from some live radiostations and it works pretty well :)
My use case is to record 10 seconds and recognize them and repeat this process with the next 10 seconds. If the recognized track differs from the previous one, then it should be added to the DB – it works very well for 99% of recognized tracks :)

Recently I discovered that it doesn't work for some tracks (but that tracks are successfully recognized by a Shazam app on iPhone). I use the app store version (not Siri integration).

For example, its something strange with the track "The Only Magic" by Alloise. I tried to split full track for 10 seconds segments and this track can't be recognized at all. The same with 20-second segments, but the iOS app works fine with all segments (also it sends track to Shazam after 6-7 seconds). 
 
File with the 20-second sample: [segment_2780000.mp3.zip](https://github.com/dotX12/ShazamIO/files/7989219/segment_2780000.mp3.zip) (sorry, Github doesn't support .mp3 files, so it needs to be archived)

I'll look for implementation on the weekend (some time is needed to understand `DecodedMessage` and signature generator), but if you have some ideas why it might not work – it would be very helpful!

I tried to increase `MAX_TIME_SECONDS`, remove audio normalization, but it still doesn't work.

**Comment by dotX12** [comment]
@Vadimkin, Hello, I'm having problems recognizing this song using the official addon for Google Chrome, I listened to the song 5-7 times completely and only 2 times I managed to recognize it, it seems that there are problems with shazam.


![image](https://user-images.githubusercontent.com/64792903/152279557-bc149a41-05c4-4d5d-ba4e-423e799b6a16.png)
![image](https://user-images.githubusercontent.com/64792903/152279522-7a3e25e3-533b-4230-b1ab-10d59cffa801.png)

**Comment by Vadimkin** [comment]
Yes, it looks like something strange – with Siri it takes a little bit more time, but the track is recognized, but with the iOS app (I can't reproduce "success case" anymore) and with chrome extension it doesn't work.

Thank you very much for this help! I'll ping you if I'll discover something new about this issue, but looks like we can close this issue for now since it's something wrong on the shazam side.

**Comment by ariandemnika** [comment]
Hi @Vadimkin this issue is still, Shazam app recognizes (Using iOS), but the ShazamIO it's not recognizing. im sending chunk files, trying with 5 seconds, 7 seconds, 10 seconds, chunking the whole mp3 file, and no results. I've made the process of chunking automated, you can try using the api: https://shazam-api.com/api/recognize 
Post request:
```
{
    "url": "https://example.com/music.mp3"
}
```
Then it will return an url in response, which will show the data when completed, it will add every track found in a JSON object from every chunk "Now using 10 second chunks".

Is there any way to fix it ?

Best regards
