### ISSUE TITLE
Question: is there any limit to api calls?

### ISSUE THREAD

**Issue by asmiyusau** [dotX12/ShazamIO#16]
Basically, title. I know some apis have a limit of calls per day. Does shazam have one?

**Comment by dotX12** [comment]
> Basically, title. I know some apis have a limit of calls per day. Does shazam have one?
@asmiyusau,
I didn't test specifically, but a PR was accepted: https://github.com/dotX12/ShazamIO/pull/8/files which added user agent randomization.

I myself tested about 300 songs a day and did not run into problems, in another issure The person said that he recognizes songs from the radio, I think there is a lot more song flow than 300 a day :)
