### ISSUE TITLE
InvalidFieldError

### ISSUE THREAD

**Issue by Dysta** [dotX12/ShazamIO#21]
I got an `InvalidFieldError` when I shazam the audio from these urls:
- https://twitter.com/chainsawmanpv/status/1522975612750737408?s=21&t=UaABnjSKzQBr6g7uueEejw
- https://www.instagram.com/p/CdL_qy6hBOf/

Full error:
```InvalidFieldError: Invalid data at path [0, matches]: init() missing 1 required positional argument: 'channel'```

### Code
```py
shazam = Shazam()
out = await shazam.recognize_song(data=data_path)
result = Serialize.full_track(data=out)
if not result.track:
    return

youtube_data = await shazam.get_youtube_data(link=result.track.youtube_link)
info = Serialize.youtube(youtube_data)
```
where `data_path` is a path to the audio file downloaded from the two previous URLs (example path: `/tmp/my_app/aze456sd`)

### Debug
After debug, the error is raised by the line `Serialize.full_track(data=out)` with `out` equal to (convert to JSON here)
https://gist.github.com/Dysta/6c2620f2b1fef49e479aed14ad996196

**Comment by dotX12** [comment]
@Dysta,
Hi, thanks for reporting the bug and sorry for the long time reply.

Corrected!

**Comment by dotX12** [comment]
@Dysta https://github.com/dotX12/ShazamIO/releases/tag/0.1.1.1
