### ISSUE TITLE
woow!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [dotX12/ShazamIO#24]
hello my friend!congratulations but please can you help me run your amazing project to search music from shazam?
I run this but nothing pip install shazamio

**Comment by dotX12** [comment]
@KENPOKASMMA1982, Hello!
Check: https://github.com/dotX12/ShazamIO/tree/master/examples
There are many examples on how to use it.
Don't forget to install ffmpeg!

Have a nice day :)

**Comment by KENPOKASMMA1982** [comment]
MY FRIEND THANKS SO MUCH WHERE ANSWER ME!BUT I RUN THIS AND DONT WORK!  pip install shazamio

**Comment by dotX12** [comment]
@KENPOKASMMA1982, give more information, send an error or screenshots of errors.

**Comment by KENPOKASMMA1982** [comment]
Collecting pydub<0.25.0,>=0.24.1
  Using cached pydub-0.24.1-py2.py3-none-any.whl (30 kB)
Requirement already satisfied: numpy<2.0.0,>=1.20.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from shazamio) (1.22.3)
Requirement already satisfied: dataclass-factory<3.0.0,>=2.10.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from shazamio) (2.14)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (1.7.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (1.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (2.0.12)
Requirement already satisfied: attrs>=17.3.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (21.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (1.3.0)
Requirement already satisfied: idna>=2.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.7.4->shazamio) (3.3)
Installing collected packages: pydub
  Attempting uninstall: pydub
    Found existing installation: pydub 0.25.1
    Uninstalling pydub-0.25.1:
      Successfully uninstalled pydub-0.25.1
Successfully installed pydub-0.24.1
WARNING: There was an error checking the latest version of pip.

**Comment by dotX12** [comment]
> Collecting pydub<0.25.0,>=0.24.1 Using cached pydub-0.24.1-py2.py3-none-any.whl (30 kB) Requirement already satisfied: numpy<2.0.0,>=1.20.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from shazamio) (1.22.3) Requirement already satisfied: dataclass-factory<3.0.0,>=2.10.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from shazamio) (2.14) Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (6.0.2) Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (4.0.2) Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (1.7.2) Requirement already satisfied: aiosignal>=1.1.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (1.2.0) Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (2.0.12) Requirement already satisfied: attrs>=17.3.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (21.4.0) Requirement already satisfied: frozenlist>=1.1.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from aiohttp<4.0.0,>=3.7.4->shazamio) (1.3.0) Requirement already satisfied: idna>=2.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.7.4->shazamio) (3.3) Installing collected packages: pydub Attempting uninstall: pydub Found existing installation: pydub 0.25.1 Uninstalling pydub-0.25.1: Successfully uninstalled pydub-0.25.1 Successfully installed pydub-0.24.1 WARNING: There was an error checking the latest version of pip.

everything is ok during installation, where is the error?

**Comment by KENPOKASMMA1982** [comment]
MY FRIEND SOMETHING GOING WRONG!I CANT SOLVE IT!

**Comment by dotX12** [comment]
Please describe the problem in more detail, what are your mistakes, upload a video, what operations are you performing.

**Comment by dotX12** [comment]
> MY FRIEND TELL ME PLEASE SOMETHING FIRST!THIS PROJECT IS FOR SEARCHING MUSIC ALSO?

Yes

**Comment by dotX12** [comment]
I close this topic, because his question does not concern libraries and installations.  google government and get:

> WARNING: There was an error checking the latest version of pip.
