### ISSUE TITLE
Hang on very small recognition request

### ISSUE THREAD

**Issue by Dronablo** [dotX12/ShazamIO#27]
Hi!

If we would try to call Shazam.recognize_song with input less than 128 audio samples it will hang forever:
https://github.com/dotX12/ShazamIO/blob/7ec7a3dd0b0731f57118dd218704a73e43be2614/shazamio/api.py#L270-L271

https://github.com/dotX12/ShazamIO/blob/7ec7a3dd0b0731f57118dd218704a73e43be2614/shazamio/algorithm.py#L94-L96

Maybe introducing something like MIN_AUDIO_SECONDS will help?

**Comment by dotX12** [comment]
> Hi!
> 
> If we would try to call Shazam.recognize_song with input less than 128 audio samples it will hang forever:
> 
> https://github.com/dotX12/ShazamIO/blob/7ec7a3dd0b0731f57118dd218704a73e43be2614/shazamio/api.py#L270-L271
> 
> https://github.com/dotX12/ShazamIO/blob/7ec7a3dd0b0731f57118dd218704a73e43be2614/shazamio/algorithm.py#L94-L96
> 
> Maybe introducing something like MIN_AUDIO_SECONDS will help?

Greetings, I'm currently on vacation and would be grateful if you could do a PR.

**Comment by Dronablo** [comment]
Well, it says 403 when I try to make push of my branch with fix. Am I do something wrong or some additional permissions needed?

**Comment by dotX12** [comment]
@Dronablo Fork the repository and push commits to your repository. Then you can open a pull request

**Comment by Dronablo** [comment]
Fixed in #31.
