### ISSUE TITLE
Someone selling your project as API

### ISSUE THREAD

**Issue by BostyBro** [dotX12/ShazamIO#29]
Does they have license for selling your free project?
https://rapidapi.com/mirzahadjaevaguzal/api/shazam-song-recognizer/pricing

**Comment by dotX12** [comment]
> Does they have license for selling your free project?
> https://rapidapi.com/mirzahadjaevaguzal/api/shazam-song-recognizer/pricing


Hi, looks like a complete copy of my library :)))

I'm only sure of this:
https://rapidapi.com/apidojo/api/shazam/
When I started developing this library, they already existed.

**Comment by dotX12** [comment]
I have an MIT license that does not prohibit the modification and sale of the product. One condition:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

But we won't know if he copied this library or not :)
