### ISSUE TITLE
Running async function inside FastAPI

### ISSUE THREAD

**Issue by auyeskhan-n** [dotX12/ShazamIO#33]
How to run shazamio inside async function of FastAPI?

Running like this gives "RuntimeError: This event loop is already running in python"
```
@app.post("/music_recognition")
async def music_recognition(file: Request):
    ...........
    async def get_music_info():
        out = await shazam.recognize_song('temp.mp3')

    loop = asyncio.get_event_loop()
    loop.run_until_complete(get_music_info())
     ..........
```
Is there way to run shazam.recognize_song() not async?

**Comment by dotX12** [comment]
@auyeskhan-n , hello!
It's much easier than you thought :)
You don't need access to loop.


```python3
import uvicorn
from fastapi import Depends
from fastapi import FastAPI
from fastapi import File
from fastapi import UploadFile

from shazamio import Shazam

app = FastAPI()


def get_shazamio():
    shazam = Shazam()
    return shazam


@app.post("/recognize")
async def recognize_file(
    shazam_service: Shazam = Depends(get_shazamio), file: UploadFile = File(...)
):
    out = await shazam_service.recognize_song(await file.read())
    return out


if __name__ == '__main__':
    uvicorn.run(app)


![image](https://user-images.githubusercontent.com/64792903/187476414-d02189c6-a4a7-4c15-95d0-944d2ed1bc71.png)


```
INFO:     Started server process [451608]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:59393 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:59393 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:59394 - "POST /recognize HTTP/1.1" 200 OK
```

**Comment by auyeskhan-n** [comment]
Thanks! Works smooth :)
