### ISSUE TITLE
about_artist.py doe snot work

### ISSUE THREAD

**Issue by nicolad76** [dotX12/ShazamIO#35]
Hi,
I love this code but while testing it I found out that about_artist.py, regardless the id I use, always returns

` DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "C:\Development\Sampler\Python\get_artist_by_id.py", line 16, in <module>
    loop.run_until_complete(main())
  File "C:\Users\nicola\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Development\Sampler\Python\get_artist_by_id.py", line 9, in main
    serialized = Serialize.artist(about_artist)
  File "C:\Users\nicola\AppData\Local\Programs\Python\Python310\lib\site-packages\shazamio\serializers.py", line 23, in artist
    return FACTORY_ARTIST.load(data, Union[ArtistV2, ArtistInfo])
  File "C:\Users\nicola\AppData\Local\Programs\Python\Python310\lib\site-packages\dataclass_factory\factory.py", line 222, in load
    return self.parser(class_)(data)
  File "C:\Users\nicola\AppData\Local\Programs\Python\Python310\lib\site-packages\dataclass_factory\parsers.py", line 99, in union_parser
    raise UnionParseError("No suitable parsers in union found for `%s`" % data, errors)
dataclass_factory.exceptions.UnionParseError: No suitable parsers in union found for `{'message': 'Not found'}`
Suberrors:
  * get_complex_parser.<locals>.complex_parser: ArtistV2.__init__() missing 1 required positional argument: 'artist'
  * get_complex_parser.<locals>.complex_parser: ArtistInfo.__init__() missing 2 required positional arguments: 'name' and 'verified'`

I installed python 3.16 and latest Shazamio library.
I think the URL https://www.shazam.com/discovery/v3/en/GB/web/artist is not valid anymore.

**Comment by dotX12** [comment]
@nicolad76, Hello, yes indeed.

https://www.shazam.com/services/amapi/v1/catalog/RU/artists/1235974098?extend=artistBio%2CbornOrFormed%2CeditorialArtwork%2Corigin&views=full-albums%2Cfeatured-albums%2Clatest-release%2Ctop-music-videos%2Csimilar-artists%2Ctop-songs%2Cplaylists

I'll fix it, try within a couple of days.

Models have changed a lot, optional "additives" have appeared
```
extend: artistBio,bornOrFormed,editorialArtwork,origin
views: full-albums,featured-albums,latest-release,top-music-videos,similar-artists,top-songs,playlists
```

**Comment by dotX12** [comment]
@nicolad76,

Does this look normal to you as a user?
Depending on the (views, extends) params model will either include the required data or not.

request:

```python3

about_artist = await shazam.artist_about(
        artist_id,
        query=ArtistQuery(
            views=[
                ArtistView.FULL_ALBUMS,
                ArtistView.FEATURED_ALBUMS,
                ArtistView.LATEST_RELEASE,
                ArtistView.TOP_MUSIC_VIDEOS,
                ArtistView.SIMULAR_ARTISTS,
            ],
            extend=[
                ArtistExtend.ARTIST_BIO,
                ArtistExtend.BORN_OF_FORMED,
                ArtistExtend.EDITORIAL_ARTWORK,
                ArtistExtend.ORIGIN,
            ],
        ),
    )
    serialized = Serialize.artist_v2(about_artist)
```
    
  and small model (I've only sketched a small model so far.)
    
```python3
    ArtistResponse(errors=[],
               data=[ArtistV3(id='1300793014',
                              type='artists',
                              attributes=ArtistAttribute(genre_names=['Hip-Hop/Rap'],
                                                         name='BONES',
                                                         url='https://music.apple.com/gb/artist/bones/1300793014',
                                                         artist_bio='BONES is '
                                                                    'a beacon '
                                                                    'of light '
                                                                    'in emo '
                                                                    'rap, '
                                                                    'upholding ... .... ...'
                                                                    'hip-hop.'))])
```
 OR (In case of error)
 ```
 ArtistResponse(errors=[ErrorModel(id='65B2IANZ7AW77BHTDC4TVHUFBI',
                                  title='Resource Not Found',
                                  detail='Resource with requested id was not '
                                         'found',
                                  status='404',
                                  code='40400')],
               data=[])
```

**Comment by dotX12** [comment]
there are a lot of questions to the API developers why data is a list, but I prefer not to touch it, suddenly there can be more than 1 element (WHAT ???)

**Comment by nicolad76** [comment]
> @nicolad76,
> 
> Does this look normal to you as a user? Depending on the (views, extends) params model will either include the required data or not.
>

This looks perfect to me

**Comment by dotX12** [comment]
I'm planning to release an update in the next few days.

**Comment by dotX12** [comment]
Unfortunately, I haven't been feeling very well for the last week, I'll try to update by the end of the month! Thanks for using the library!

**Comment by nicolad76** [comment]
sorry to hear that. No rush for me of course. Take your time.

**Comment by dotX12** [comment]
@nicolad76, 
https://github.com/dotX12/ShazamIO/blob/2715d435df83e936d978ddec4ef2711dfe29deb1/examples/about_artist.py

**Comment by dotX12** [comment]
Working on an open source takes a lot of time... Work, study and personal life, but despite the delay, it was done!
