### ISSUE TITLE
question: Recognizing multiple songs at the same time

### ISSUE THREAD

**Issue by JuanFran928** [dotX12/ShazamIO#37]
Hello, is it possible to recognize multiple songs with the method `recognize_song('dora.mp3')` at the same time?

I have some mp3s files downloaded that I want to identify its name, it is possible to make this task asynchronously or do I need to make it one by one as the for loop goes on.
My goal is to speed up the process of identifying the whole list of mp3s files. I've tried this task with threads and with asyncio but there's no such a difference in time.

Regards

**Comment by dotX12** [comment]
Unfortunately it is not possible to transfer multiple songs for identification, shazam supports the identification of one song per operation.
It is possible that multiprocessing can help you if you have a very large set of songs.

**Comment by JuanFran928** [comment]
thank you very much @dotX12

**Comment by dotX12** [comment]
Fixed in 0.5.0.
See comment: https://github.com/shazamio/ShazamIO/issues/76#issuecomment-1961610344
