### ISSUE TITLE
Question: How can I get the title and the artist name?

### ISSUE THREAD

**Issue by Lolimipsu** [dotX12/ShazamIO#38]
Hi, I would like to ask how can I get the name and artist name only?

![image](https://user-images.githubusercontent.com/44487404/201296305-cd734b4b-a5df-47f8-bfaf-c3a06ba9c129.png)

I'm trying to get only the title and subtitle but I don't know how can I get them from the raw format, is there a way to get it? 
thank you in advance.
![image](https://user-images.githubusercontent.com/44487404/201298387-34c8a5c0-a4e1-466e-8f90-2fbe9dd809a8.png)

**Comment by dotX12** [comment]
@Lolimipsu, hello!

```python3
    out = await shazam.recognize_song("data/dora.ogg")
    print(out)

    serialized = Serialize.full_track(out)
    print(serialized.track.title)
    print(serialized.track.subtitle)
```

**Comment by dotX12** [comment]
or
```
out["track"]["title"]
out["track"]["subtitle"]
```

**Comment by Lolimipsu** [comment]
> or
> 
> ```
> out["track"]["title"]
> out["track"]["subtitle"]
> ```
ohh so this is how I should do it, thank you!

**Comment by Lolimipsu** [comment]
ohh so this is how I should do it, thank you @dotX12  !
