### ISSUE TITLE
Get artist top tracks 

### ISSUE THREAD

**Issue by Epic-R-R** [dotX12/ShazamIO#47]
I use this artist_id 1304716885 for get details from artist and it work fine 
but when I want to get top track from this artist it show me error
`shazamio.exceptions.FailedDecodeJson: Check args, URL is invalid
URL- https://cdn.shazam.com/shazam/v3/en/GB/web/-/tracks/artisttoptracks_1304716885?startFrom=0&pageSize=3&connected=&channel=` 
I use this artist_id 201896832 you put in the example file and it works but for another artist, it gives an error

**Comment by Epic-R-R** [comment]
It also gives me an error when I use the top track country code  method
`shazamio.exceptions.FailedDecodeJson: Check args, URL is invalid
URL- https://www.shazam.com/shazam/v3/en/GB/web/-/tracks/ip-country-chart-?pageSize=200&startFrom=0`

**Comment by Daxitdon** [comment]
i am also getting same error

**Comment by dotX12** [comment]
Hello @Epic-R-R, @Daxitdon.
Sorry for such a long wait for this issue.
artisttoptracks is deprecated.

Now syntax:

```python3

import asyncio
from shazamio import Shazam, Serialize
from shazamio.schemas.artists import ArtistQuery
from shazamio.schemas.enums import ArtistView


async def main():
    shazam = Shazam()
    artist_id = 1081606072

    about_artist = await shazam.artist_about(
        artist_id,
        query=ArtistQuery(
            views=[
                ArtistView.TOP_SONGS,
            ],
        ),
    )
    serialized = Serialize.artist_v2(about_artist)
    for i in serialized.data[0].views.top_songs.data:
        print(i.attributes.name)


loop = asyncio.get_event_loop_policy().get_event_loop()
loop.run_until_complete(main())

```

Result:

```
'...And to Those I Love, Thanks for Sticking Around'
'Kill Yourself (Part III)'
'Paris'
'2nd Hand'
'$Outh $Ide $Uicide (feat. Pouya)'
'Carrollton'
'122 Days'
'O Pana!'
'For the Last Time'
"Runnin' Thru the 7th with My Woadies"
```


Web:

![image](https://user-images.githubusercontent.com/64792903/236382077-ce07826b-1b82-49be-aba2-6d76f8674d2a.png)

**Comment by dotX12** [comment]
Released: https://pypi.org/project/shazamio/0.4.0.0/
