### ISSUE TITLE
feature: Accept `offset` in `search_track`

### ISSUE THREAD

**Issue by cc00010** [dotX12/ShazamIO#48]
Please consider adding `offset` parameter to `search_track`

**Comment by cc00010** [comment]
Here's the patch:

```patch
diff --git a/shazamio/api.py b/shazamio/api.py
index 0feaa0d..21653ad 100644
--- a/shazamio/api.py
+++ b/shazamio/api.py
@@ -274,7 +274,7 @@ class Shazam(Converter, Geo, Request):
             headers=self.headers(),
         )
 
-    async def search_track(self, query: str, limit: int = 10) -> Dict[str, Any]:
+    async def search_track(self, query: str, limit: int = 10, start_from: int = 0) -> Dict[str, Any]:
         """
         Search all tracks by prefix
             :param query: Track full title or prefix title
@@ -287,6 +287,7 @@ class Shazam(Converter, Geo, Request):
             ShazamUrl.SEARCH_MUSIC.format(
                 query,
                 limit,
+                start_from,
                 language=self.language,
             ),
             headers=self.headers(),
diff --git a/shazamio/misc.py b/shazamio/misc.py
index b8e4742..d4fcb19 100644
--- a/shazamio/misc.py
+++ b/shazamio/misc.py
@@ -49,7 +49,7 @@ class ShazamUrl:
     )
     SEARCH_MUSIC = (
         "https://www.shazam.com/services/search/v3/en/GB/web/search?query={}"
-        "&numResults={}&offset=0&types=songs"
+        "&numResults={}&offset={}&types=songs"
     )
     LISTENING_COUNTER = "https://www.shazam.com/services/count/v2/web/track/{}"
 
```

**Comment by dotX12** [comment]
> Please consider adding `offset` parameter to `search_track`

Thanks for your input, I don't have much time right now and would be grateful if you could release a PR with this change! I will accept it.

**Comment by dotX12** [comment]
> Here's the patch:
> 
> ```diff
> diff --git a/shazamio/api.py b/shazamio/api.py
> index 0feaa0d..21653ad 100644
> --- a/shazamio/api.py
> +++ b/shazamio/api.py
> @@ -274,7 +274,7 @@ class Shazam(Converter, Geo, Request):
>              headers=self.headers(),
>          )
>  
> -    async def search_track(self, query: str, limit: int = 10) -> Dict[str, Any]:
> +    async def search_track(self, query: str, limit: int = 10, start_from: int = 0) -> Dict[str, Any]:
>          """
>          Search all tracks by prefix
>              :param query: Track full title or prefix title
> @@ -287,6 +287,7 @@ class Shazam(Converter, Geo, Request):
>              ShazamUrl.SEARCH_MUSIC.format(
>                  query,
>                  limit,
> +                start_from,
>                  language=self.language,
>              ),
>              headers=self.headers(),
> diff --git a/shazamio/misc.py b/shazamio/misc.py
> index b8e4742..d4fcb19 100644
> --- a/shazamio/misc.py
> +++ b/shazamio/misc.py
> @@ -49,7 +49,7 @@ class ShazamUrl:
>      )
>      SEARCH_MUSIC = (
>          "https://www.shazam.com/services/search/v3/en/GB/web/search?query={}"
> -        "&numResults={}&offset=0&types=songs"
> +        "&numResults={}&offset={}&types=songs"
>      )
>      LISTENING_COUNTER = "https://www.shazam.com/services/count/v2/web/track/{}"
>  
> ```

Hello! Added and renamed start_from to offset.

**Comment by dotX12** [comment]
Released: https://pypi.org/project/shazamio/0.4.0.0/
