### ISSUE TITLE
DeprecationWarning about event loop.

### ISSUE THREAD

**Issue by sosopoet** [dotX12/ShazamIO#49]
Since upgrading to Linux Mint 21 (ubuntu 20.04) I'm seeing

DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()

Seems my Python is now version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

[Paul Cornelius says (on StackExchange) ](https://stackoverflow.com/questions/73361664/asyncio-get-event-loop-deprecationwarning-there-is-no-current-event-loop) "code will run on Python3.10 but as of 3.11 it will be an error to call asyncio.get_event_loop when there is no running loop in the current thread. Since you need loop as an argument, apparently, you must explicitly create and set it.

I tried pasting something like his suggestion, into my script in place of the 'loop = asyncio.get_event_loop()' bit, but just got a TypeError instead...

**Comment by dotX12** [comment]
`https://github.com/dotX12/ShazamIO/blob/master/examples/recognize_song.py`

**Comment by dotX12** [comment]
> Since upgrading to Linux Mint 21 (ubuntu 20.04) I'm seeing
> 
> DeprecationWarning: There is no current event loop loop = asyncio.get_event_loop()
> 
> Seems my Python is now version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
> 
> [Paul Cornelius says (on StackExchange) ](https://stackoverflow.com/questions/73361664/asyncio-get-event-loop-deprecationwarning-there-is-no-current-event-loop) "code will run on Python3.10 but as of 3.11 it will be an error to call asyncio.get_event_loop when there is no running loop in the current thread. Since you need loop as an argument, apparently, you must explicitly create and set it.
> 
> I tried pasting something like his suggestion, into my script in place of the 'loop = asyncio.get_event_loop()' bit, but just got a TypeError instead...

https://github.com/dotX12/ShazamIO/blob/b05b1eb2f8e714f3b3b19e201786f59aef711317/examples/recognize_song.py#L1-L15

**Comment by dotX12** [comment]
https://github.com/dotX12/ShazamIO/blob/b05b1eb2f8e714f3b3b19e201786f59aef711317/examples/recognize_song.py#L14-L15

Thank you for reporting this, not all examples have it fixed, but here is the corrected version.
