### ISSUE TITLE
I want to install this package in python 3.6

### ISSUE THREAD

**Issue by YashMakan** [dotX12/ShazamIO#5]
Due to some circumstances, I can only use Python 3.6. How can I use this package with python 3.6? Kindly suggest

**Comment by dotX12** [comment]
@YashMakan, HI, I just checked the build for 3.6.8 - everything works stably!

**Comment by dotX12** [comment]
New version - 0.0.3
Added support for 3.6
https://pypi.org/project/shazamio/

**Comment by YashMakan** [comment]
Thank you for the support.
