### ISSUE TITLE
(Request) - search lyrics

### ISSUE THREAD

**Issue by Sansekai** [dotX12/ShazamIO#77]
Can add search lyrics?

**Comment by dotX12** [comment]
@Sansekai, hello!
It's worth considering that not all songs have lyrics, but if they do, this function will find them.

![image](https://github.com/dotX12/ShazamIO/assets/64792903/113007c0-cf74-4cda-872c-8cb1a4e3d535)

```python3
import asyncio

from shazamio import Shazam


def find_lyrics(data) -> list[str] | None:
    if data.get("track"):
        if data["track"].get("sections"):
            for element in data["track"]["sections"]:
                if element.get("type") == "LYRICS":
                    return element.get("text")
    return None


async def main():
    shazam = Shazam()
    out = await shazam.recognize_song("data/Joey_Bada_THE_REV3NGE.mp3")
    print(find_lyrics(out))


loop = asyncio.get_event_loop_policy().get_event_loop()
loop.run_until_complete(main())

```

**Comment by dotX12** [comment]
You can always look at the JSON that shazam returns and get the necessary data, for example, the lyrics of a song.
`Serialize` was created for simple scenarios; there is not always time to keep it up to date :(

**Comment by moeinrahimi1** [comment]
there is no lyrics for this song: https://www.shazam.com/song/1737268895/masteh-cheshaat
although it has lyrics on shazam page
