### ISSUE TITLE
Quota or changes to the API recently ? 

### ISSUE THREAD

**Issue by kimherman** [dotX12/ShazamIO#86]
Hi, 
I wrote some code that runs different audio files through the shazamio library and gives me back a tracklist but I noticed something strange yesterday. I retested an old run and where I would get 102 matches for a list of files mid january 2024 I now (12 feb 2024) only get 4 and all the other chunks error out in my logging with the following error : 

```
Error with chunk_5.mp3: Check args, URL is invalid
URL- https://amp.shazam.com/discovery/v5/en-US/GB/iphone/-/tag/B8057BCE-C9BF-421D-8273-B7974DF3CEA3/8F4BD112-2382-4E5C-A050-14D86830B82F?sync=true&webv3=true&sampling=true&connected=&shazamapiversion=v3&sharehub=true&hubv5minorversion=v5.1&hidelb=true&video=v3
Error with chunk_6.mp3: Check args, URL is invalid
URL- https://amp.shazam.com/discovery/v5/en-US/GB/iphone/-/tag/AF1F5AC9-6B84-4652-BA89-2568DB3E56F8/2BFF82F8-5A28-47F4-9A35-7C9AEF3D8FAB?sync=true&webv3=true&sampling=true&connected=&shazamapiversion=v3&sharehub=true&hubv5minorversion=v5.1&hidelb=true&video=v3

etc..... 

```
1) has anyone else run into the same issue recently ? 
2) Was there any change in the library, shazam API or quota that would explain this because the code & audio files are identical ?

**Comment by MnLgt** [comment]
same thing here

**Comment by kimherman** [comment]
@MnLgt Seems that this issue is very closely related to [issue 81](https://github.com/dotX12/ShazamIO/issues/81)
Will test out the workaround from the comments in my code today

**Comment by kimherman** [comment]
@MnLgt The workaround works, but as expected, because of the retries and delay times to circumvent the limits, any run of multiple files takes **a lot** longer.

**Comment by dotX12** [comment]
All discussion is now at https://github.com/dotX12/ShazamIO/issues/81
