### ISSUE TITLE
recognize_song raises FileNotFoundError even if file is present

### ISSUE THREAD

**Issue by SetUpSim** [dotX12/ShazamIO#9]
I'm writing a Teleram bot with Shazam-like functionality. Under the hood it downloads the file or voice message sent by user, gets its path and tries to recognize the song from file located on that path.

My code:

```import os
import telebot
import requests
import asyncio
from shazamio import Shazam

TOKEN = None

with open("TOKEN") as f:
    TOKEN = f.read().strip()

bot = telebot.TeleBot(TOKEN, parse_mode=None)

def download_file_and_return_name(file_id):
    file_info = bot.get_file(file_id)
    filename = file_info.file_path.split("/")[-1]
    resp = requests.get('https://api.telegram.org/file/bot{0}/{1}'.format(TOKEN, file_info.file_path))
    with open(filename, "wb") as f:
        f.write(resp.content)
    return filename

async def recognize(path):
    shazam = Shazam()
    print(path)
    print(os.path.exists(path))
    out = await shazam.recognize_song(path)
    print(out)


@bot.message_handler(content_types=["audio", "voice"])
def handle_audio(message):
    filename = download_file_and_return_name(message.voice.file_id if message.content_type == "voice" else message.audio.file_id)
    # loop = asyncio.get_event_loop()
    # loop.run_until_complete(recognize(filename))
    asyncio.run(recognize(filename))

bot.polling()
```

Unfortunately, recognize_song(file_path) method raises FileNotFoundError even if file is present, which is logged by `print(os.path.exists(path))`
Console log:

```
C:\Users\stass\workspace\shazamBotProject\venv\Scripts\python.exe C:/Users/stass/workspace/shazamBotProject/main.py
C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
file_40.oga
True
C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\stass\workspace\shazamBotProject\main.py", line 42, in <module>
    bot.polling()
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\telebot\__init__.py", line 514, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\telebot\__init__.py", line 573, in __threaded_polling
    raise e
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\telebot\__init__.py", line 536, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\telebot\util.py", line 117, in raise_exceptions
    raise self.exception_info
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\stass\workspace\shazamBotProject\main.py", line 40, in handle_audio
    asyncio.run(recognize(filename))
  File "C:\Users\stass\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\stass\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\stass\workspace\shazamBotProject\main.py", line 30, in recognize
    out = await shazam.recognize_song("file_35.ogg")
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\shazamio\api.py", line 220, in recognize_song
    audio = self.normalize_audio_data(file)
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\shazamio\converter.py", line 45, in normalize_audio_data
    audio = AudioSegment.from_file(BytesIO(song_data))
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\pydub\audio_segment.py", line 685, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\stass\workspace\shazamBotProject\venv\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\stass\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\stass\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1
```

I haven't used the `loop = asyncio.get_event_loop()
loop.run_until_complete(main())` construct from the example because it raises `RuntimeError: There is no current event loop in thread 'WorkerThread2'`

**Comment by dotX12** [comment]
@SetUpSim, Hello!

I have a question for you:
If you are using the Telebot library, why are you sending a naked request to API telegrams, this library already has methods for downloading files.

I already have a project that you want to implement:
https://github.com/dotX12/ShazamBot

An asynchronous library for working with telegram is used here (aiogram).I have a question for you:
If you are using the Telebot library, why are you sending a naked request to API telegrams, this library already has methods for downloading files.

I already have a project that you want to implement:
https://github.com/dotX12/ShazamBot

An asynchronous library for working with telegram is used here (aiogram).

**Comment by SetUpSim** [comment]
A piece of Telebot documentation:
```
# getFile
# Downloading a file is straightforward
# Returns a File object
import requests
file_info = tb.get_file(file_id)

file = requests.get('https://api.telegram.org/file/bot{0}/{1}'.format(API_TOKEN, file_info.file_path))
```
So I'm sending a naked request to Telegram API to download files because `Telebot` appears to have no API method for doing this.
Thank you for your advice on `aiogram`, but I'm currently mastering another library. And here a strange bug appears, so I would like you to maybe clear the things out for me.

**Comment by dotX12** [comment]
@SetUpSim,
In fact, I changed almost nothing, your code worked for me, only changed the launch of an asynchronous function in a loop.
https://carbon.now.sh/qH4Jci9HPh2uboq9tNDz

![image](https://user-images.githubusercontent.com/64792903/123607762-d9c67f00-d806-11eb-9d8a-ed500d59f344.png)

**Comment by dotX12** [comment]
Console:

![image](https://user-images.githubusercontent.com/64792903/123607919-f82c7a80-d806-11eb-8e21-65f08bc60b3a.png)

File hierarchy:

![image](https://user-images.githubusercontent.com/64792903/123607969-07132d00-d807-11eb-8b2d-9b2cf82dc3f6.png)

**Comment by SetUpSim** [comment]
Your code still raises FileNotFoundError for me. 
What's your Python version? Mine is 3.9.0

**Comment by SetUpSim** [comment]
@dotX12 Your code still raises FileNotFoundError for me.
What's your Python version? Mine is 3.9.0

> 
> 
> Console:
> 
> ![image](https://user-images.githubusercontent.com/64792903/123607919-f82c7a80-d806-11eb-8e21-65f08bc60b3a.png)
> 
> File hierarchy:
> 
> ![image](https://user-images.githubusercontent.com/64792903/123607969-07132d00-d807-11eb-8b2d-9b2cf82dc3f6.png)

Z

**Comment by SetUpSim** [comment]
@dotX12 Your code still raises FileNotFoundError for me.
What's your Python version? Mine is 3.9.0

**Comment by dotX12** [comment]
Check if your files are saved?
If so, maybe they will be saved to a different location, relative to your bot file.

**Comment by dotX12** [comment]
@SetUpSim, Ahhh, sorry man...
```
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
  
```
  You need to install ffmpgeg.

**Comment by SetUpSim** [comment]
Yep, that was the thing. Thank you
